language: node_js
node_js:
  - "10"
cache: npm
install:
  - npm ci
  - npx lerna bootstrap
before_script:
  - npm run build:semantic
  - npm run build
  # - npm run pkg
script:
  - npm test
  - npm run e2e
